#! /bin/bash

sCompany='#@all' ;
sUser= ;
while [ "x$1" != "x" ] ; do
	if [ "$1" = "-c" ] ; then 
		shift ;
		sCompany=$1 ;
	else
		sUser=$1 ;
	fi
	
	shift ;
done

sUser=${sUser:-www} ;

sshConfigFile=~/.ssh/servers.xml ;

XsltFileList=$(mktemp -t 'cssh-xslt-XXXXXXX' ) ;

if [ "$sCompany" != '#@all' ] ; then
	cat > "${XsltFileList}" <<EOD
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
<xsl:output method="text" encoding="ISO-8859-1"/>
<xsl:template match="/"><xsl:apply-templates select="/servers/server"/></xsl:template>
<xsl:template match="/servers/server"><xsl:if test="company='${sCompany}'"><![CDATA[ ${sUser}@]]><xsl:value-of select="host"/></xsl:if></xsl:template>
</xsl:stylesheet>
EOD
else
	cat > "${XsltFileList}" <<EOD
<?xml version="1.0" encoding="ISO-8859-1"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
<xsl:output method="text" encoding="ISO-8859-1"/>
<xsl:template match="/"><xsl:apply-templates select="/servers/server"/></xsl:template>
<xsl:template match="/servers/server"><![CDATA[ ${sUser}@]]><xsl:value-of select="host"/></xsl:template>
</xsl:stylesheet>
EOD
fi

xsltproc "${XsltFileList}" "${sshConfigFile}" ;
echo ' ' ;
rm -f "${XsltFileList}";

