#! /bin/bash

if [ "x$1" = 'x' ] ; then
	echo "Usage: $0 [-i [identity_file] [-i [identity_file] ...]] [user@]machine [[user@]machine ...]" ;
	exit 0;
fi

sCatKey="" ;
if [ "$1" = "-i" ] ; then
	while [ "$1" = "-i" ] ; do
		shift ;
		sFile="$1" ;
		if [ -r "${sFile}" ] ; then
			shift ;
		else
			sFile="${HOME}/.ssh/id_rsa.pub" ;
		fi ;
		sCatKey="${sCatKey} '${sFile}'" ;
	done
	sCatKey="cat ${sCatKey}" ;
fi

if [ "${sCatKey}" = "" ] ; then
	if [ "x$SSH_AUTH_SOCK" != "x" ] && ssh-add -L >/dev/null 2>&1; then
    sCatKey = "ssh-add -L" ;
  fi
fi

if [ -z "$(eval "${sCatKey}")" ]; then
  echo "$0: ERROR: No identities found" >&2
  exit 1
fi

while [ "x$1" != 'x' ] ; do
	sHost=$1 ;
	
	echo " - Copy key on '${sHost}' -" ;
	{ eval "${sCatKey}" ; } | ssh ${sHost%:} "umask 077; test -d .ssh || mkdir .ssh ; cat >> .ssh/authorized_keys" || exit 1 ;
	
	shift ;
done
